version: '3.8'

services:
  mongoinit:
    image: mongo
    restart: "no"
    command: >
      mongosh --host mongodb0:27017 -u ${MONGO_INITDB_ROOT_USERNAME} -p ${MONGO_INITDB_ROOT_PASSWORD}  --eval 
      '
      rs.initiate({
        "_id" : "rs0",
        "members" : [
          {
            "_id" : 0,
            "host" : "mongodb0:27017"
          },
          {
            "_id" : 1,
            "host" : "mongodb1:27017"
          },
          {
            "_id" : 2,
            "host" : "mongodb2:27017"
          }
        ]
      });
      '